Wechsel von Select zu SelectVariable
symcon/CSVZipExport pull request #5
Opened 2022-03-31 10:16 UTC by Sunnyka98

Da der Standard für die Variablenauswahl "SelectVariable" ist wurde das Konfigurationsfeld von "Select" zu "SelectVariable" gewechselt und das Feld Filter erstmal ausgeblendet. Um die Funktionalität für den Ursprünglichen Auftraggeber mit dem Modul "SyncMySQL" zu behalten, wird das Feld "Select" und "Filter" trotzdem angezeigt, wenn das Modul installiert ist.

2022-03-31 14:39 UTC, paresy requested changes
Nur die 3 Kleinigkeiten.

Und mir ist aufgefallen, dass der E-Mail Intervall auf 700px Breite steht. Das sieht doof aus. Das darf gerne kleiner wie die anderen Elemente. Magst du das noch mit anpassen?

Außerdem kann man auf Export drücken und es kommt keine Fehlermeldung, wenn keine Variable ausgewählt ist. Das wäre auch schön zu korrigieren. Das wird Niels nämlich ganz sicher beim Review testen 😄

2022-03-31 14:39 UTC, paresy commented on CSVZipExport/form.json
> +                    "width": "550px"
Wofür war die Änderung erforderlich?

2022-03-31 14:39 UTC, paresy commented on CSVZipExport/module.php
> +        if (IPS_ModuleExists('{7E122824-E4D6-4FF8-8AA1-2B7BB36D5EC9}')) {
Der Kommentar aus dem anderen Modul war toll. Den hätte ich hier auch gerne:

`//If the module "SyncMySQL" is install, get other options`

2022-03-31 14:41 UTC, paresy commented on CSVZipExport/form.json
> +            "requiredLogging": 1
Das müssten wir noch per "unset" entfernen. Aktuell stört es die Konsole nicht - aber langfristig wollen wir dies validieren und dann könnte es ärger geben.

2022-04-01 07:12 UTC, Sunnyka98 commented on CSVZipExport/form.json
> +                    "width": "550px"
Stil, die Textbox + Button war kürzer als der Rest.

2022-04-01 10:40 UTC, merged